server:
  port: 12000
spring:
  application:
    name: iep-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/MissQinMeng/tensquare-config.git
          search-paths: /**
         
      label: master
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    instance-id: tensquare-config12000
    prefer-ip-address: true
